//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 09:58:26 PM BRT 
//


package com.viglet.turing.plugins.otca.af.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFAttributeDefTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AFAttributeDefTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="text"/>
 *     &lt;enumeration value="textarea"/>
 *     &lt;enumeration value="radio"/>
 *     &lt;enumeration value="checkbox"/>
 *     &lt;enumeration value="select"/>
 *     &lt;enumeration value="list"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AFAttributeDefTypeEnum")
@XmlEnum
public enum AFAttributeDefTypeEnum {

    @XmlEnumValue("text")
    TEXT("text"),
    @XmlEnumValue("textarea")
    TEXTAREA("textarea"),
    @XmlEnumValue("radio")
    RADIO("radio"),
    @XmlEnumValue("checkbox")
    CHECKBOX("checkbox"),
    @XmlEnumValue("select")
    SELECT("select"),
    @XmlEnumValue("list")
    LIST("list");
    private final String value;

    AFAttributeDefTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AFAttributeDefTypeEnum fromValue(String v) {
        for (AFAttributeDefTypeEnum c: AFAttributeDefTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
