//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 09:58:26 PM BRT 
//


package com.viglet.turing.plugins.otca.af.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFConfigUnitTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AFConfigUnitTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="entity"/>
 *     &lt;enumeration value="candidate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AFConfigUnitTypeEnum")
@XmlEnum
public enum AFConfigUnitTypeEnum {

    @XmlEnumValue("entity")
    ENTITY("entity"),
    @XmlEnumValue("candidate")
    CANDIDATE("candidate");
    private final String value;

    AFConfigUnitTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AFConfigUnitTypeEnum fromValue(String v) {
        for (AFConfigUnitTypeEnum c: AFConfigUnitTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
