//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 09:58:26 PM BRT 
//


package com.viglet.turing.plugins.otca.af.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFTermVariationCaseEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AFTermVariationCaseEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ci"/>
 *     &lt;enumeration value="cs"/>
 *     &lt;enumeration value="ucs"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AFTermVariationCaseEnum")
@XmlEnum
public enum AFTermVariationCaseEnum {

    @XmlEnumValue("ci")
    CI("ci"),
    @XmlEnumValue("cs")
    CS("cs"),
    @XmlEnumValue("ucs")
    UCS("ucs");
    private final String value;

    AFTermVariationCaseEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AFTermVariationCaseEnum fromValue(String v) {
        for (AFTermVariationCaseEnum c: AFTermVariationCaseEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
