//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 09:58:26 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dev.nstein.com/tme-authority-file/4.10", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.viglet.turing.plugins.otca.af.xml;
