//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 09:58:26 PM BRT 
//


package com.viglet.turing.plugins.otca.af.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFTermVariationAccentEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AFTermVariationAccentEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ai"/>
 *     &lt;enumeration value="as"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AFTermVariationAccentEnum")
@XmlEnum
public enum AFTermVariationAccentEnum {

    @XmlEnumValue("ai")
    AI("ai"),
    @XmlEnumValue("as")
    AS("as");
    private final String value;

    AFTermVariationAccentEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AFTermVariationAccentEnum fromValue(String v) {
        for (AFTermVariationAccentEnum c: AFTermVariationAccentEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
