//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.24 at 09:29:47 AM BRT 
//


package com.viglet.turing.plugins.otca.response.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServerResponseEntityExtractorResultTermHierarchyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServerResponseEntityExtractorResultTermHierarchyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Base" type="{}ServerResponseEntityExtractorResultTermHierarchyBaseType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServerResponseEntityExtractorResultTermHierarchyType", propOrder = {
    "base"
})
public class ServerResponseEntityExtractorResultTermHierarchyType {

    @XmlElement(name = "Base")
    protected ServerResponseEntityExtractorResultTermHierarchyBaseType base;

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link ServerResponseEntityExtractorResultTermHierarchyBaseType }
     *     
     */
    public ServerResponseEntityExtractorResultTermHierarchyBaseType getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerResponseEntityExtractorResultTermHierarchyBaseType }
     *     
     */
    public void setBase(ServerResponseEntityExtractorResultTermHierarchyBaseType value) {
        this.base = value;
    }

}
