




  CREATE TABLE "TURSEARCHRESULTSCOMPONENT" 
   (	"ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(768 BYTE), 
	"DESCRIPTION" VARCHAR2(3000 BYTE), 
	"RESULTS_PER_PAGE" NUMBER(10,0), 
	"DISPLAY_VIEW_ID" VARCHAR2(40 BYTE), 
	"TITLE" VARCHAR2(3000 BYTE), 
	"HEADER" VARCHAR2(3000 BYTE), 
	"FOOTER" VARCHAR2(3000 BYTE), 
	"THUMBNAIL" VARCHAR2(40 BYTE), 
	"RENDERINGTYPE" CHAR(1 BYTE) DEFAULT '0' NOT NULL ENABLE, 
	"TTL" VARCHAR2(400 BYTE), 
	"KEYWORD_ATTR" VARCHAR2(20 CHAR), 
	"PAGE_ATTR" VARCHAR2(20 CHAR), 
	"END_POINT" VARCHAR2(200 CHAR) DEFAULT NULL, 
	"FACET_ATTR" VARCHAR2(20 CHAR), 
	 PRIMARY KEY ("ID")
  ) ;


CREATE TABLE "TURSEARCHTOOLBARCOMPONENT" 
   (	"ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(768 BYTE), 
	"DESCRIPTION" VARCHAR2(3000 BYTE), 
	"RESULTS_CHANNEL_ID" VARCHAR2(40 BYTE), 
	"DISPLAY_VIEW_ID" VARCHAR2(40 BYTE), 
	"TITLE" VARCHAR2(3000 BYTE), 
	"HEADER" VARCHAR2(3000 BYTE), 
	"FOOTER" VARCHAR2(3000 BYTE), 
	"TTL" VARCHAR2(400 BYTE), 
	"THUMBNAIL" VARCHAR2(40 BYTE), 
	"RENDERINGTYPE" CHAR(1 BYTE) DEFAULT '0' NOT NULL ENABLE, 
	"KEYWORD_ATTR" VARCHAR2(20 CHAR), 
	"ALLOWED_QS_ATTRS" VARCHAR2(200 CHAR), 
	"AC_END_POINT" VARCHAR2(200 CHAR), 
	 PRIMARY KEY ("ID")
);
