//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.24 at 09:29:47 AM BRT 
//


package com.viglet.turing.plugins.otca.response.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServerResponseGetSupportedEncodingsResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServerResponseGetSupportedEncodingsResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Encodings" type="{}ServerResponseGetSupportedEncodingsResultEncodingsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServerResponseGetSupportedEncodingsResultType", propOrder = {
    "encodings"
})
public class ServerResponseGetSupportedEncodingsResultType {

    @XmlElement(name = "Encodings")
    protected ServerResponseGetSupportedEncodingsResultEncodingsType encodings;
    @XmlAttribute(name = "Name")
    protected String name;

    /**
     * Gets the value of the encodings property.
     * 
     * @return
     *     possible object is
     *     {@link ServerResponseGetSupportedEncodingsResultEncodingsType }
     *     
     */
    public ServerResponseGetSupportedEncodingsResultEncodingsType getEncodings() {
        return encodings;
    }

    /**
     * Sets the value of the encodings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerResponseGetSupportedEncodingsResultEncodingsType }
     *     
     */
    public void setEncodings(ServerResponseGetSupportedEncodingsResultEncodingsType value) {
        this.encodings = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
